# Generated by Django 2.2.3 on 2019-09-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lishitianqi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=16)),
                ('date', models.DateField()),
                ('maxt', models.IntegerField()),
                ('mint', models.IntegerField()),
                ('weath', models.CharField(max_length=20)),
                ('windd', models.CharField(max_length=20)),
                ('windp', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'lishitianqi',
                'managed': False,
            },
        ),
    ]
