# Generated by Django 2.2.3 on 2019-09-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history_weath', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citys',
            fields=[
                ('city', models.CharField(max_length=16, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'citys',
                'managed': False,
            },
        ),
    ]
